# Generated by Django 5.0.6 on 2025-10-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='survey_uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='survey',
            name='file_category',
            field=models.CharField(blank=True, choices=[('report', 'Report'), ('fieldbook', 'Field Book'), ('drawing', 'Drawing'), ('specification', 'Specification'), ('bom', 'Bill of Materials'), ('survey_data', 'Survey Data'), ('design_calc', 'Design Calculation'), ('permit', 'Permit/Approval'), ('as_built', 'As-Built'), ('photo', 'Photo/Documentation'), ('contract', 'Contract'), ('minutes', 'Minutes of Meeting'), ('correspondence', 'RFI/Correspondence'), ('gis', 'GIS/Geospatial'), ('other', 'Other')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='file_ext',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='file_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
