# Generated by Django 5.0.6 on 2025-10-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_file_survey_file_category_survey_file_ext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='file_category',
            field=models.CharField(blank=True, choices=[('drawing_arch', 'Drawing - Architectural'), ('drawing_struct', 'Drawing - Structural'), ('drawing_mep', 'Drawing - MEP'), ('shop_drawing', 'Shop Drawing'), ('as_built', 'As-Built'), ('specification', 'Specification'), ('method_statement', 'Method Statement'), ('itp', 'Inspection & Test Plan (ITP)'), ('qa_qc_record', 'QA/QC Record'), ('geotech_report', 'Geotechnical Report'), ('survey_report', 'Survey Report'), ('fieldbook', 'Field Book'), ('daily_report', 'Daily Report'), ('progress_report', 'Progress Report'), ('testing_report', 'Testing/Commissioning Report'), ('schedule_program', 'Schedule/Program'), ('boq_bom', 'BOQ/Bill of Materials'), ('rfi', 'RFI/Correspondence'), ('submittal', 'Submittal'), ('permit_approval', 'Permit/Approval'), ('contract', 'Contract/Agreement'), ('change_order', 'Change Order/Variation'), ('site_instruction', 'Site Instruction'), ('inspection_request', 'Inspection Request'), ('ncr', 'Non-Conformance Report (NCR)'), ('material_certificate', 'Material Certificate'), ('safety_hse', 'Safety/HSE Document'), ('photo', 'Photo/Documentation'), ('gis', 'GIS/Geospatial'), ('design_calc', 'Design Calculation'), ('payment_certificate', 'Payment Certificate'), ('transmittal', 'Transmittal'), ('minutes', 'Minutes of Meeting'), ('other', 'Other')], max_length=32, null=True),
        ),
    ]
