# Generated by Cascade on 2025-10-26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_alter_survey_file_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="recovered_file",
            field=models.FileField(blank=True, null=True, upload_to="survey_recovered/%Y/%m/%d/"),
        ),
    ]
