# Generated by Django 5.0.6 on 2025-10-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_recovered_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='enc_chunk_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='enc_scheme',
            field=models.CharField(default='envelope-aeskw-v1', max_length=32),
        ),
        migrations.AddField(
            model_name='survey',
            name='kdf_salt_b64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='key_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='survey',
            name='wrapped_dek_b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
