# Generated by Django 5.0.6 on 2025-10-23 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_tx_hash', models.CharField(max_length=100)),
                ('public_anchor_tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('anchor_batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('private_block_number', models.BigIntegerField(blank=True, null=True)),
                ('public_block_number', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='surveys.survey')),
            ],
        ),
    ]
