# Generated by Cascade on 2025-10-26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_address_profile_company_profile_job_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="data_kek_b64",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="data_kek_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
